name:  sysfoo-ci-pipeline
on: [push]
jobs:
  sysfoo-ci-job:
    runs-on:
      - ubuntu-latest
    steps:
      - name: hello-world
        run: echo "Welcome to SYSFOO"
        
      - name: Code Checkout
        uses: actions/checkout@v6.0.1
        
      - name: Test
        run: mvn test
        
      - name: Clean Package
        run: mvn clean
        
      - name: Package
        run: mvn package

      - name: lsit files
        run: ls -lrt target
